FROM gruffwizard/nog-base:latest as builder

FROM gruffwizard/nog-quarkus:latest as main

USER nog
COPY --from=builder /extras/theia  /home/nog/tools/theia
EXPOSE 9001

LABEL nog=true
COPY nog.sh /home/nog/tools
