FROM registry.access.redhat.com/ubi8/ubi-minimal:8.1

RUN microdnf install curl tar gzip python3 make gcc gcc-c++

# cache Java

RUN mkdir /tools

ARG JAVA_VERSION=jdk-11.0.8+10
ARG JSUM='6e4cead158037cb7747ca47416474d4f408c9126be5b96f9befd532e0a762b47'
ARG BINARY_URL='https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.8_10.tar.gz'

RUN curl -LfsSo /tools/openjdk.tar.gz ${BINARY_URL}
RUN echo "${JSUM} */tools/openjdk.tar.gz" | sha256sum -c -

RUN cd /tools && tar -xvzf openjdk.tar.gz && rm openjdk.tar.gz
RUN mv /tools/jdk-11.0.8+10  /tools/java

RUN rm -rf /tools/java/man

# cache maven

ARG MAVEN_VERSION=3.6.3
ARG MSUM='c35a1803a6e70a126e80b2b3ae33eed961f83ed74d18fcd16909b2d44d7dada3203f1ffe726c17ef8dcca2dcaa9fca676987befeadc9b9f759967a8cb77181c0'
ARG MAVEN_URL=https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
RUN curl -LfsSo /tools/maven.tar.gz ${MAVEN_URL}
RUN echo "${MSUM} */tools/maven.tar.gz" | sha512sum -c -
RUN cd /tools && tar -xvzf maven.tar.gz && rm maven.tar.gz

RUN mv /tools/apache-maven-${MAVEN_VERSION} /tools/maven

# cache theia in /extras/theia

RUN curl --silent --location https://rpm.nodesource.com/setup_12.x | bash -
RUN curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo |  tee /etc/yum.repos.d/yarn.repo

RUN microdnf install yarn git libxml2 xmlstarlet

RUN mkdir -p /extras/theia
COPY package.json /extras/theia/
WORKDIR /extras/theia/

RUN yarn
RUN yarn theia build

LABEL nog=true
