FROM gruffwizard/nog-base:latest as builder

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.1

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

COPY --from=builder /etc/yum.repos.d/yarn.repo  /etc/yum.repos.d/yarn.repo

RUN microdnf install yarn git shadow-utils  gcc glibc-devel zlib-devel libstdc++

RUN useradd -ms /bin/bash nog

USER nog

# copy over tools

COPY --from=builder /tools  /home/nog/tools

ENV JAVA_HOME=/home/nog/tools/java
ENV PATH=/home/nog/tools/maven/bin:/home/nog/tools/java/bin:$PATH
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

# validate tools

RUN java -version
RUN mvn -version


EXPOSE 8080
EXPOSE 9001
EXPOSE 5005

COPY nog.sh /home/nog/tools

RUN mkdir -p /home/nog/src

RUN mkdir -p /home/nog/.m2

RUN mkdir -p /home/nog/quarkus-quickstarts

WORKDIR /home/nog/src

#ENTRYPOINT  ["/home/nog/tools/runner.sh"]

LABEL nog=true
